version: 0.1
phases:
  install:
    commands:
    - npm install --silent
    - aws cloudformation package --template-file template.yaml --s3-bucket github-2-lambda --output-template-file output-template.yaml
artifacts:
  type: zip
  files:
  - '**/*'
